### ISSUE TITLE
Doesn't automatically pull in python-dnspython on Debian 9

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [HenriWahl/dhcpy6d#14]
When installing version 0.7.1(-1) on a fresh Debian 9.4.0 installation, it doesn't pull in the necessary dependencies.

This creates an error message about missing the DNS module during installation, and it's not at all obvious how to fix the error afterwards (when the DUID needs to be made by-hand).

**Comment by JamesTheAwesomeDude** [comment]
(for some reason, even when DUID generation fails, the package is still tagged as fully-installed, so not even `apt-get install -f` will finish up the configuration after the dependencies have been manually acquired.)

**Comment by HenriWahl** [comment]
Thanks for the hint. Actually the package is still built on a Debian 8 because it worked, so it might be a good idea to port the packaging to Debian 9. I will check this asap.
After resolving the DNS issue - does it work at all?

**Comment by JamesTheAwesomeDude** [comment]
Yeah, it's actually a pretty great server! Once I had generated and inserted the DUID manually, it really works well. 😄👍

*\<offtopic\>*  
Only thing that seemed "off" was that it temporarily semi-broke the OS's default DNS suffix (the IPv4 server WAS advertising it; the IPv6 server was NOT: it showed up in Win10 Task Manager, but most applications seemed not to resolve the domains); I fixed it by hard-coding the network's specific domain `$sitexxx$.hsv.al.us.xn--l3h.$mydomain$` into the config file. (The IPv4 server is the canonical/authoritative source of site domain information)

but that's pretty easy to implement with probably a DHCP(v4) client hook or something like that if it ever becomes an issue

**Comment by HenriWahl** [comment]
Thanks for the hint - added the info to documentation.

Regarding the offtopic: what was the configuration statement to tell clients about the DNS suffix?

**Comment by HenriWahl** [comment]
Now with https://github.com/HenriWahl/dhcpy6d/commit/db1c16b5104289fd07cfb427b6e9cd013af78e85 the package builds with Debian 9 and has the python-dns dependencies included.

**Comment by HenriWahl** [comment]
Where did you get the binary from?

**Comment by HenriWahl** [comment]
Uploaded fixed package - thanks for the hint!
