### ISSUE TITLE
Option 59 support

### ISSUE THREAD

**Issue by FelixJacobi** [HenriWahl/dhcpy6d#16]
I am considering to switch from the ISC DHCP server, as the MAC thing there is annoying.

As I am dependent on support for supplying the PXE boot parameter via DHCPv6 (Option 59, described in RFC 5970),  I started to implement this for dhcpy6d: https://github.com/HenriWahl/dhcpy6d/compare/master...FelixJacobi:add-rfc5970 (WIP, no PR yet).

Should already work, but has no support for configurable URL yet.

**Comment by HenriWahl** [comment]
Cool man - I am on vacation right now but maybe you are ready when I am back.

**Comment by FelixJacobi** [comment]
Just created a WIP PR (#17) which contains a basic implementation.
