### ISSUE TITLE
Windows only uses the first two IP addresses from clients.conf?

### ISSUE THREAD

**Issue by FelixJacobi** [HenriWahl/dhcpy6d#23]
Hi,

I tried to assign several static IP addresses via DHCPv6 to a client using this entry in a `clients.conf`:

~~~
[client_4]
address = fda9:b38a:2445:1001::4 2001:470:539f:1001::4 fda9:b38a:2445:1001:921b:eff:feac:c691 2001:470:539f:1001:921b:eff:feac:c691
class = default_enp3s0.1001
hostname = vm-server
mac = 90:1b:0e:ac:c6:91
~~~

It seems that Windows just uses the first two entries from the `address` list (the one ending with `::4`).

If I swap them with the two other ones, these one are used instead. Has someone seen something similar? Could this be a limit like in macOS which only accepts one IPv6 address via DHCPv6? (I researched but didn't found anything pointing out that)

**Comment by HenriWahl** [comment]
Can you make sure that all addresses have been submitted to the client? Logging the session with Wireshark on the client could give more insights.

**Comment by FelixJacobi** [comment]
Hi,

I didn't have time until now to investigate using Wireshark. However, an ISC DHCP client on Debian 10 in the same network works fine and receives all addresses configured in `clients.conf`. So I think at least the network is probably fine. I will take further investigations as in the near future.

**Comment by HenriWahl** [comment]
I never used more than 2 addresses for Windows clients so if this is a bug or a feature of Windows it never came up.
