### ISSUE TITLE
No bootfiles in older versions

### ISSUE THREAD

**Issue by tobiWu** [HenriWahl/dhcpy6d#28]
I've got some struggle with configuring bootfiles until I noticed that in the stable version 0.7.3 the bootfile option is missing in config.py. In version 0.7.99 the bootfiles option can be set. 
Unfortunately there was no hint about this in changelogs or documentation. Could you please update this to avoid this struggle to other users?

**Comment by HenriWahl** [comment]
Sorry for the confusion. I will look at it.

Did you try 0.7.99 by the way?

**Comment by tobiWu** [comment]
Version 0.7.99 is working great on Ubuntu 18.04.

**Comment by HenriWahl** [comment]
Great. It got ported to Python 3 and will appear as 1.0 soon.
