### ISSUE TITLE
log_file config should not be mandaroty

### ISSUE THREAD

**Issue by crosser** [HenriWahl/dhcpy6d#29]
dhcpy6d allows logging via syslog, but when logging is enabled, it requires logfile to be specified, to be a regular file (disallowing `/dev/null`) and to be owned by the daemon.

On a production system, one typically uses syslog (possibly remote) for logging, and having a separate log file to take care of is an unnecessary complication.

I think that dhcpy6d should allow to configure logging via syslog only, and not require log file to be present or configured.

**Comment by HenriWahl** [comment]
You are absolutely right, makes sense not to require a log file. I will have a look for this.

**Comment by HenriWahl** [comment]
Please check the testing packages from https://dhcpy6d.ifw-dresden.de/download

**Comment by HenriWahl** [comment]
Fixed in latest release 1.0.1.
