### ISSUE TITLE
generic database driver

### ISSUE THREAD

**Issue by grinapo** [HenriWahl/dhcpy6d#3]
I'm using postgresql. Need I say more? ;-) 
You should use a generic db api instead of specific fiddling, so you can support various db engines with much less efforts.

**Comment by HenriWahl** [comment]
Brona added PostgreSQL support in his fork at https://github.com/brona/dhcpy6d/commit/ac4e51c8e734b63af109d43aa7133bed4c9af359#diff-c947434f1a6282eade971a9ff228dcf7R714 with no much effort as the used SQL syntax is alredy pretty generic.
I will look at this when next time doing some development - promised.

**Comment by grinapo** [comment]
Umm, it's 97% formatting, it's basically a trivial change. Why don't you merge it? Shall I create a plain fork without the formatting fixes?

**Comment by HenriWahl** [comment]
Time time... if you have some can you integrate the PostgreSQL from Brona, add the config stuff and do a pull request?

**Comment by HenriWahl** [comment]
OK then it should be enough to have config options like store_db_user and store_db_pass instead of store_mysql_user, store_mysql_pass, store_postgresql_user and the likes.

**Comment by grinapo** [comment]
Indeed. The patch is trivial.

**Comment by HenriWahl** [comment]
Can you please check your PostgreSQL with latest commit f1f4a7b0f6166dee5ef00ded72ca8478254a22de? Config parameters are now as stated above - replace all *_mysql_* by *_db_*.
Let me know if it works for you - thanks!

**Comment by HenriWahl** [comment]
Last commits contained a bug, now 72adb2aa1d980a5a4ebc8120d9ff157fc4351df3 is the real test candidate. Also available at http://dhcpy6d.ifw-dresden.de/download/.

**Comment by HenriWahl** [comment]
I found the SQL schemes at https://dhcpy6d.ifw-dresden.de/documentation/sql/ not fully working for PostgreSQL. Can you please help to improve them?

**Comment by grinapo** [comment]
I'll test them, takes a bit of time, doing plenty of stuff in parallel. :-)

**Comment by HenriWahl** [comment]
Any news or still much parallel stuff? :-)

**Comment by HenriWahl** [comment]
Any news or still interested?

**Comment by grinapo** [comment]
Interested: yes; news: no; unfortunately I am right now really busy with restructuring large parts of the network including the machine I was played on. I try to process that part of my todo list... :-( sorry.

**Comment by HenriWahl** [comment]
OK... I am working on making the SQL scheme MySQL-independent. I will let you know of any news.

**Comment by HenriWahl** [comment]
Last commit has working PostgreSQL support. There is no binary available yet but could you test it?
There is a modified SQL scheme file for PostgreSQL too,

**Comment by HenriWahl** [comment]
Binaries now avaliable with PostgeSQL support at https://dhcpy6d.ifw-dresden.de/download/
