### ISSUE TITLE
How to install as user?

### ISSUE THREAD

**Issue by miri64** [HenriWahl/dhcpy6d#33]
Usually when installing a python package as non-root user using

```sh
pip install git+https://github.com/HenriWahl/dhcpy6d
```

the startup script gets installed to `~/.local/bin`. However, the installation process above puts some non-standard files in `etc`, `var`, and `usr` within ~/.local/lib/python3.X/site-packages/etc/dhcpy6d.conf. Uninstalling the package does not delete these files properly. Is there a way to install `dhcpy6d` using setuptools as a user?

**Comment by HenriWahl** [comment]
Honestly I never tried to install it this way so I do not know nothing how it uninstalls.

As dhcpy6d at least need to be started as root to open the needed socket - why should it be installed as user via pip?

**Comment by miri64** [comment]
> Honestly I never tried to install it this way so I do not know nothing how it uninstalls.

I just removed them, since where they were they were of no use. If you like, I can look into a more "pythonic" way for the installation.

> As dhcpy6d at least need to be started as root to open the needed socket - why should it be installed as user via pip?

That would have been indeed my next question, actually; if non-standard ports (so ports for which you can open a socket as non-root) would be possible with dhcpy6d :sweat_smile:. We are considering using dhcpy6d as a drop-in DHCPv6 server for prefix delegation our border router example in our IoT operating system [RIOT](https://github.com/RIOT-OS/RIOT/tree/master/examples/gnrc_border_router). Currently, for users that have root access to their machine we use the ISC's Kea as the DHCPv6 server. For people that don't have root access to their machine (sadly in an academic environment that seems to happen sometimes ;-)) we only have a propriatery alternative to configure the prefixes. Kea set's some path not necessarily writable for users at compile time to write their pidfile and stuff like that, so we were hoping a python based alternative would not have this issues when setting the port within the non-restricted range (which the border router could also be configured to as a client).

**Comment by HenriWahl** [comment]
> I just removed them, since where they were they were of no use. If you like, I can look into a more "pythonic" way for the installation.

Good idea - as long as it will not interfere with package building beause package are the main distribution method.


> That would have been indeed my next question, actually; if non-standard ports (so ports for which you can open a socket as non-root) would be possible with dhcpy6d. 

This was possible but because of having no apparent use for it and simply default port is 547 this feature was removed. Might as well simple become reimplemented again.

> We are considering using dhcpy6d as a drop-in DHCPv6 server for prefix delegation our [border router example](https://github.com/RIOT-OS/RIOT/tree/master/examples/gnrc_border_router) in our IoT operating system [RIOT](https://github.com/RIOT-OS/RIOT). 

Sounds interesting - how are you going to tell the client that another port for sending requests to server should be used?

**Comment by miri64** [comment]
> > We are considering using dhcpy6d as a drop-in DHCPv6 server for prefix delegation our [border router example](https://github.com/RIOT-OS/RIOT/tree/master/examples/gnrc_border_router) in our IoT operating system [RIOT](https://github.com/RIOT-OS/RIOT).
> 
> Sounds interesting - how are you going to tell the client that another port for sending requests to server should be used?

It's the other way around, I guess. The server would be set to a non-restricted port, when we notice that the user does not have root access, when starting the node (i.e. the client) in our bootstrapping script. As this is merely thought to be an example that new users can just run and see things happening, we have full control of the environment. This is of course not meant for production.

**Comment by miri64** [comment]
> > I just removed them, since where they were they were of no use. If you like, I can look into a more "pythonic" way for the installation.
> 
> Good idea - as long as it will not interfere with package building beause package are the main distribution method.

See https://github.com/HenriWahl/dhcpy6d/pull/34

**Comment by miri64** [comment]
Will open a PR about the other things discussed here, once I have something working (currently I have the problem that our client and your server do not play nice... will investigate first on whos end that is before opening an issue).

**Comment by HenriWahl** [comment]
What client are you using?

**Comment by miri64** [comment]
> What client are you using?

Our own minimalistic implementation for RIOT. It is only supporting requesting Prefix Delegation. The current observation is, that after the client sends out a SOLICIT, I get a REPLY (instead of the expected ADVERTISE) back without the configured prefix. But somehow this also causes our client to go crazy and starting to spam SOLICITs.

**Comment by HenriWahl** [comment]
Well... this apparently is caused by dhcpy6d not knowing the client. It will retrieve the client's MAC address from its neighbor cache, but if there is no entry yet it sends some dummy REPLY to get the client asking again. The REPLY will cause the neighbor cache to get the needed info about the client.

**Comment by miri64** [comment]
> Well... this apparently is caused by dhcpy6d not knowing the client. It will retrieve the client's MAC address from its neighbor cache, but if there is no entry yet it sends some dummy REPLY to get the client asking again. The REPLY will cause the neighbor cache to get the needed info about the client.

Mh... the info should be in the neighbor cache, but thanks for the hint, I will have a look tomorrow.

**Comment by HenriWahl** [comment]
I noticed the servers neighbor cache not containing the client's MAC at the SOLICIT - it just gets filled when the server asks itself for it by sending something like a REPLY.

**Comment by HenriWahl** [comment]
At https://github.com/HenriWahl/dhcpy6d/blob/master/doc/dhcpy6d.conf.rst the setting 

```
ignore_mac = yes|no
    If serving only for delivering addresses regardless of classes (e.g. on PPP interface) MACs do not need to be investigated.
```
might be of interest for you in case you do not need any MAC information.

**Comment by miri64** [comment]
Ok, the client is indeed not in the neighbor cache (yet) when this happens. However,

1. It is definitely faulty behavior that our client starts spamming SOLICITs on the REPLY, I will focus on fixing that first
2. When enforcing the client's address to be in the neighbor cache before the client sends its solicit, I still get some SOLICIT/REPLY exchanges which then stop at some point with the client still being left without a prefix :confused:

**Comment by HenriWahl** [comment]
How do you enforce this? On the server side?

**Comment by miri64** [comment]
Pinging the node before the client sends its first solicit (since the server starts after the client there is some time between starting the server and the second solicit).

**Comment by HenriWahl** [comment]
By ping6 to its fe80::/64 address?

**Comment by HenriWahl** [comment]
>     2. When enforcing the client's address to be in the neighbor cache before the client sends its solicit, I still get some SOLICIT/REPLY exchanges which then stop at some point with the client still being left without a prefix confused

Can you show some logging info of dhcpy6d?

**Comment by miri64** [comment]
> By ping6 to its fe80::/64 address?

Yepp.

**Comment by miri64** [comment]
> > ```
> > 2. When enforcing the client's address to be in the neighbor cache before the client sends its solicit, I still get some SOLICIT/REPLY exchanges which then stop at some point with the client still being left without a prefix confused
> > ```
> 
> 
> Can you show some logging info of dhcpy6d?

Will do later.

**Comment by miri64** [comment]
#34 was reverted
