### ISSUE TITLE
reload configuration without killing and starting dhcpy6d?

### ISSUE THREAD

**Issue by PepeOnAChair** [HenriWahl/dhcpy6d#37]
Hello,
thank you for this DHCP server, which supports MAC addresses...

Is it somehow possible to reload configuration of clients without the need to kill the process first and then starting it again? Some kind of atomic configuration reload, so the service will not be stopped for some short time. We are expecting to run dhcpy6d for some 10000 devices.

Best regards
Pep.

**Comment by HenriWahl** [comment]
The easiest way to do so is storing the config in a database. Currently supported types are MySQL/MariaDB, PostgreSQL and SQLite.

**Comment by PepeOnAChair** [comment]
Thank you, I`ll try it.
Pep.
