### ISSUE TITLE
Centos repository not working

### ISSUE THREAD

**Issue by Nowatel** [HenriWahl/dhcpy6d#40]
dhcpy6d-stable                                                                                                                                                16 kB/s | 9.6 kB     00:00
Errors during downloading metadata for repository 'dhcpy6d-stable':
  - Status code: 404 for https://dhcpy6d.de/files/repo/stable/centos/repodata (IP: 185.199.109.153)
Error: Failed to download metadata for repo 'dhcpy6d-stable': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

**Comment by HenriWahl** [comment]
I did not post this yet as still being testing the transition. dhcpy6d has moved to dhcpy6d.de with all new keys so you will have to fix your repo information according to https://dhcpy6d.de/download.

**Comment by HenriWahl** [comment]
@Nowatel - does the new URL work for you?

**Comment by Nowatel** [comment]
Sorry for the delay, yes it's working now.

**Comment by HenriWahl** [comment]
Good news.
