### ISSUE TITLE
debian/control: Drop dh-systemd from Build-Depends?

### ISSUE THREAD

**Issue by FelixJacobi** [HenriWahl/dhcpy6d#55]
The package `dh-systemd` and its utils were considered obsolete and superseded by `dh_installsystemd` which is part of debhelper directly. 

Could we drop that build dependency? At least in the newest Ubuntu, the package is also not available anymore.

**Comment by HenriWahl** [comment]
You are right - doesn't exist on Debian 11 anymore too. So it apparently safely can be removed.
