### ISSUE TITLE
Some questions about the database

### ISSUE THREAD

**Issue by ycq177** [HenriWahl/dhcpy6d#60]
HI，bro！
1. How to increase support for other databases? For example; mongodb. 2. How to independently design new address features for specific users to use. 3. Can dhcpy6d only be used for assigning IPv6 addresses? Does it also support the allocation of IPv4 addresses? It is more competitive to allocate two types of addresses.
 Thank you very much！

**Comment by HenriWahl** [comment]
Hi @ycq177,
to answer your questions:

1. In theory one should be simply able to add new type of databases. The current SQL ones should be abstractly enough implemented so that other types could be used as backends as well.
2. What exactly do you mean?
3.  Yes, it is only designed to be used with IPv6 addresses. There are plenty IPv4 DHCP servers available. Its main purpose was and is to work in parallel and help transition by being able to use MAC addresses too,

Regards

**Comment by ycq177** [comment]
[Dear.docx](https://github.com/HenriWahl/dhcpy6d/files/9075699/Dear.docx)

**Comment by ycq177** [comment]
> Hi @ycq177, to answer your questions:
> 
> 1. In theory one should be simply able to add new type of databases. The current SQL ones should be abstractly enough implemented so that other types could be used as backends as well.
> 2. What exactly do you mean?
> 3. Yes, it is only designed to be used with IPv6 addresses. There are plenty IPv4 DHCP servers available. Its main purpose was and is to work in parallel and help transition by being able to use MAC addresses too,
> 
> Regards

[Dear HenriWahl.docx](https://github.com/HenriWahl/dhcpy6d/files/9075703/Dear.HenriWahl.docx)

**Comment by HenriWahl** [comment]
Hi @ycq177,

please write your comments in plain text so it is easier to follow the thread.

Regards

**Comment by ycq177** [comment]
Dear HenriWahl：
Thank you, I am glad to get your sincere reply！
Regarding the second question, I will give a more detailed explanation, I hope this can help you understand my problem.
I mean how to set the address of the new feature myself, ie: not within "mac", "id", "range", "random", "fixd", "dns", like:

[address_tel]
category=tel
pattern=2001:db8::$tel$       #2001:db8::175:4045:4631
Another new question，Can it be set to a mode where no addresses are assigned to unknown clients? For example, this function is accomplished by the following settings:
[class_default]
answer=none
Finally,thank you again and look forward to your further reply, I wish you and your family a happy life and good health!

**Comment by HenriWahl** [comment]
Looks like "fixed" matches your requirement already?

`answer = none` is meant to do not react to unknown clients. This can be achieved when configuring the default class with this option like this:

```ini
[class_default]
answer = none
```
