### ISSUE TITLE
Query on the support of a type of dhcpv6 message

### ISSUE THREAD

**Issue by ycq177** [HenriWahl/dhcpy6d#62]
Hi,bro:
Ask whether dhcpy6d has completed the RECONFIGURE (10) message, which is used to inform the client server that there are new configuration parameters. 
RFC8415 describes this message as follows: "A server sends a Reconfigure message to a client to inform the client that the server has new or updated configuration parameters and that the client is to initiate a Renew/Reply, Rebind/Reply, or Information-request/Reply transaction with the server in order to receive the updated information.”

**Comment by HenriWahl** [comment]
Hi @ycq177,
years ago I looked at the RECONFIGURE message and quickly found that there was some authentication involved which no client understood and so I stopped all attempts to implement this.
Maybe it looks better nowadays client-wise but right now there is no support from server side.
