### ISSUE TITLE
dhcpy6d doesn't send Advertise on ppp0

### ISSUE THREAD

**Issue by ztpaul** [HenriWahl/dhcpy6d#66]
I 'apt install ppp' on my Ubuntu 24.04.

### config of /etc/ppp/chap-secrets

`111              *      111                      111.111.111.111`

### config of /etc/ppp/pppoe-server-options 
`+ipv6`

### config of /etc/dhcpy6d.conf 
```
# dhcpy6d default configuration
#
# Please see the examples in /usr/share/doc/dhcpy6d and 
# https://dhcpy6.de/documentation for more information.

[dhcpy6d]
# Interface to listen to multicast ff02::1:2.
interface = ppp0
# Do not identify and configure clients.
store_config = none
# SQLite DB for leases and LLIP-MAC-mapping.
store_volatile = sqlite
store_sqlite_volatile = /var/lib/dhcpy6d/volatile.sqlite
log = on
log_file = /var/log/dhcpy6d.log

# set to yes to really answer to clients
# not necessary in Debian where it comes from /etc/default/dhcpy6d and /etc/init.d/dhcpy6
#really_do_it = no

# Special address type which applies to all not specially
# configured clients.
[address_default]
# Choosing MAC-based addresses.
category = range
range = 1000-1fff
pattern = 2001:db8::$range$
```

**Comment by ztpaul** [comment]
I have figured out the reason, just set "ignore_mac = yes" in [dhcpy6d] section.

**Comment by HenriWahl** [comment]
Hey @ztpaul, sorry for the late reply and 👍 for finding the solution! What exactly is your use case?

**Comment by ztpaul** [comment]
> Hey @ztpaul, sorry for the late reply and 👍 for finding the solution! What exactly is your use case?

Hi @HenriWahl , I use dhcpy6d for test in my lab.
